version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/cmg/
hooks:
  BeforeInstall:
    - location: devops/scripts/maintenance_on
      timeout: 300
      runas: ec2-user
    - location: devops/scripts/prepare_environment
      timeout: 300
      runas: root
  Install:
    - location: devops/scripts/deploy
      timeout: 300
      runas: apache
permissions:
  - object: /var/www/cmg/
    pattern: "**"
    except: [/var, /pub/media]
    owner: apache
    group: apache
    mode: 550
  - object: /var/www/cmg/var
    pattern: "**"
    owner: apache
    group: apache
    mode: 777
  - object: /var/www/cmg/pub/media
    pattern: "**"
    owner: apache
    group: apache
    mode: 777
