version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/cmg/
hooks:
  BeforeInstall:
    - location: devops/scripts/prepare_environment
      timeout: 300
      runas: root
    - location: devops/scripts/maintenance_on
      timeout: 300
      runas: ec2-user
  Install:
    - location: devops/scripts/deploy
      timeout: 300
      runas: ec2-user
