version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/cmg/
hooks:
  BeforeInstall:
    - location: scripts/maintenance_on
      timeout: 300
      runas: ec2-user
  Install:
    - location: scripts/db_upgrade
      timeout: 300
      runas: ec2-user
  AfterInstall:
    - location: scripts/maintenance_off
      timeout: 300
      runas: ec2-user
