version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/cmg/
hooks:
  BeforeInstall:
    - location: devops/deployment_scripts/maintenance-on
      timeout: 300
      runas: ec2-user
    - location: devops/deployment_scripts/prepare-environment
      timeout: 300
      runas: root
    - location: devops/deployment_scripts/opcache-purge
      timeout: 300
      runas: apache
  Install:
    - location: devops/deployment_scripts/deploy
      timeout: 300
      runas: apache
  AfterInstall:
    - location: devops/deployment_scripts/set-permissions
      timeout: 300
      runas: root
