version: 0.1

phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - chmod +x bin/magento
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - composer install --no-dev
      - bin/magento setup:di:compile
      - composer dump-autoload --no-dev --optimize
      - bin/magento setup:static-content:deploy --exclude-theme=Magento/blank --exclude-theme=Magento/luma en_US
      - echo Build finished
artifacts:
  files:
    - '**/*'
