version: 0.1

phases:
  install:
    commands:
      - echo Entered the install phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - composer install --no-dev
      - php bin/magento module:enable --all
      - php bin/magento setup:di:compile
      - composer dump-autoload --no-dev --optimize
artifacts:
  files:
    - '**/*'