version: 0.1

phases:
  install:
    commands:
      - echo Entered the install phase...
  pre_build:
    commands:
      - echo Entered the pre_build phase...
      - chmod +x bin/magento
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - composer install --no-dev
      - php bin/magento setup:di:compile
      - composer dump-autoload --no-dev --optimize
      - php bin/magento setup:static-content:deploy -f
  post_build:
    commands:
      - echo Entered the post_build phase...
      - rm -rf setup/ phpserver/ dev/ *.sample *.md Dockerfile
      - echo Build completed on `date`
artifacts:
  files:
    - '**/*'
