version: 0.1

phases:
  install:
    commands:
      - echo Entered the install phase...
  build:
    commands:
      - echo Entered the build phase...
      - echo Build started on `date`
      - composer install
      - php bin/magento setup:di:compile
artifacts:
  files:
    - '**/*'