#!/bin/bash

# TODO: move me below IF

bin/magento cache:flush

if [ $(hostname) != admin01 ]; then
    exit 0
fi

bin/magento setup:upgrade --keep-generated
bin/magento maintenance:disable
bin/magento indexer:reindex \
    catalog_category_product \
    catalog_product_category \
    catalog_product_price \
    catalog_product_attribute \
    cataloginventory_stock \
    catalogsearch_fulltext
