#!/bin/bash

# TODO: move me below IF

php bin/magento cache:flush

if [ $(hostname) != admin01 ]; then
    exit 0
fi

php bin/magento setup:upgrade --keep-generated
php bin/magento maintenance:disable
