#!/usr/bin/php

<?php

if (gethostname() !== 'admin01') {
    exit(0);
}

$targetRegion = 'us-west-1';
$targetLaunchConfigurationName = 'my-launch-configuration';

function flatten(array $array) {
    $return = array();
    array_walk_recursive($array, function($a) use (&$return) { $return[] = $a; });
    return $return;
}

$targetInstanceIds = flatten(json_decode(`aws autoscaling describe-auto-scaling-groups \
    --query 'AutoScalingGroups[*].Instances[*].[InstanceId]'`, true));
$targetInstanceIdsString = implode(' ', $targetInstanceIds);

$targetInstanceIps = flatten(json_decode(`aws ec2 describe-instances --region $targetRegion \
    --instance-ids $targetInstanceIdsString --query 'Reservations[*].Instances[*].[PrivateIpAddress]'`, true));

foreach ($targetInstanceIps as $instanceIp) {
    `ssh -T $instanceIp << EOF
        cd /var/www/cmg
        sudo -u apache bin/magento maintenance:enable
EOF`;
}

// ADMIN IN MAINTENANCE
`sudo -u apache bin/magento maintenance:enable`;
// API MAINTENANCE
