#!/usr/bin/php

<?php

$sourceEnvFile      = __DIR__ . '/../templates/env.php.tmpl';
$destinationEnvFile = __DIR__ . '/../../app/etc/env.php';

$sourceEnvTmpl = file_get_contents($sourceEnvFile);
if (!$sourceEnvTmpl) {
    echo 'Cannot load env.php template file'.
    exit(1);
}

$targetRegion = 'us-west-1';
$params = [
    'test.crypt_key',
    'test.mysql.host',
    'test.mysql.dbname',
    'test.mysql.username',
    'test.mysql.password',
];
$paramsStr = implode(' ', $params);
$values = json_decode(`aws ssm get-parameters --region $targetRegion --names $paramsStr --with-decryption --query Parameters[*].Value`);

$targetEnvTmpl = str_replace($params, $values, $sourceEnvTmpl);

$res = file_put_contents($destinationEnvFile, $targetEnvTmpl);
if (!$res) {
    echo 'Cannot write to app/etc/env.php'.
    exit(1);
}

chmod($destinationEnvFile, 0644);
chown($destinationEnvFile, 'apache');
chown($destinationEnvFile, 'apache');
