#!/usr/bin/php

<?php

$envFile = __DIR__ . '/../../app/etc/env.php';

$envTmpl = file_get_contents($envFile);
if (!$envTmpl) {
    echo 'Cannot load env.php template file'.
    exit(1);
}

$targetRegion = 'us-west-1';
$params = [
    'test.crypt_key',
    'test.mysql.host',
    'test.mysql.dbname',
    'test.mysql.username',
    'test.mysql.password',
];
$paramsStr = implode(' ', $params);
$values = json_decode(`aws ssm get-parameters --region $targetRegion --names $paramsStr --with-decryption --query Parameters[*].Value`);

$res = file_put_contents($envTmpl, str_replace($params, $values, $envTmpl));
if (!$res) {
    echo 'Cannot write to app/etc/env.php'.
    exit(1);
}
