#!/usr/bin/php

<?php

$sourceEnvFile      = __DIR__ . '/../templates/env.php.tmpl';
$destinationEnvFile = __DIR__ . '/../../app/etc/env.php';

function flatten(array $array) {
    $return = array();
    array_walk($array, function($a) use (&$return) { $return[$a[0]] = $a[1]; });
    return $return;
}

$sourceEnvTmpl = file_get_contents($sourceEnvFile);
if (!$sourceEnvTmpl) {
    echo 'Cannot load env.php template file'.
    exit(1);
}

$targetRegion = 'us-west-1';
$paramNames = [
    'test.crypt_key',
    'test.mysql.host',
    'test.mysql.dbname',
    'test.mysql.username',
    'test.mysql.password',
];
$paramNamesStr = implode(' ', $paramNames);
$params = flatten(json_decode(`
    aws ssm get-parameters --region $targetRegion --names $paramNamesStr --with-decryption \
        --query Parameters[*].[Name,Value]`));

$destinationEnvTmpl = str_replace(array_keys($params), array_values($params), $sourceEnvTmpl);

$res = file_put_contents($destinationEnvFile, $destinationEnvTmpl);
if (!$res) {
    echo 'Cannot write to app/etc/env.php'.
    exit(1);
}
