#!/bin/bash

cd /var/www/cmg
chown -R apache:apache .

find . -type f -exec chmod 0644 {} \;
find . -type d -exec chmod 0755 {} \;

find bin \( -name "magento" -o -name "*.sh" \) -exec chmod 0755 {} \;

find var/ -type d -exec chmod 0777 {} \;
find pub/media/ -type d -exec chmod 0777 {} \;
