#!/bin/bash

chown -R apache:apache /var/www/cmg/

find /var/www/cmg/ -type f -exec chmod 0644 {} \;
find /var/www/cmg/ -type d -exec chmod 0755 {} \;

find /var/www/cmg/var/ -type d -exec chmod 0777 {} \;
find /var/www/cmg/pub/media/ -type d -exec chmod 0777 {} \;
