#!/bin/bash

if [ $(hostname) != admin ]; then
    exit 0
fi

bin/magento cache:flush
bin/magento setup:upgrade
bin/magento maintenance:disable

sudo find var generated vendor pub/static pub/media app/etc -type f -exec chmod g+w {} \;
sudo find var generated vendor pub/static pub/media app/etc -type d -exec chmod g+ws {} \;
sudo chown -R apache:apache .
